name: Extract Python Code as String

on:
  push:
    branches:
      - main  # Roda sempre que houver um merge na main

jobs:
  extract_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Ler código dos arquivos Python e exibir como string formatada
        run: |
          echo "Summarize.py:"
          echo '"""'
          awk '{printf "%s\\n", $0}' summarize.py | tr -d '\n' | sed -E 's/ +/ /g' | sed -E ':a;N;$!ba;s/\n/\\n/g'
          echo '"""'

          echo "Multiply.py:"
          echo '"""'
          awk '{printf "%s\\n", $0}' multiply.py | tr -d '\n' | sed -E 's/ +/ /g' | sed -E ':a;N;$!ba;s/\n/\\n/g'
          echo '"""'
