name: Update Kompany Code Nodes

on:
  push:
    branches:
      - main  # Executa o workflow sempre que houver um push na branch main

jobs:
  update_code_nodes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: pip install requests

      - name: Rodar script de atualização
        run: python update_kompany.py
